// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PixelChat.Persistence;

#nullable disable

namespace PixelChat.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914221808_NativeSpriteExports")]
    partial class NativeSpriteExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PixelChat.Models.Anchor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("FrameId", "Name");

                    b.ToTable("Anchors");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("AnimationRecipes");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimationRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimationRecipeId", "Version")
                        .IsUnique();

                    b.HasIndex("ProjectId", "AnimationRecipeId");

                    b.ToTable("AnimationRecipeVersions");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawProviderContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawProviderData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Kept");

                    b.Property<Guid?>("SourceAnimationRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceAnimationRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourcePromptRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePromptRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentAssetId");

                    b.HasIndex("SourceAnimationRecipeId");

                    b.HasIndex("SourceBatchId");

                    b.HasIndex("SourcePromptRecipeId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "ReviewStatus", "CreatedAt");

                    b.ToTable("ArtAssets");
                });

            modelBuilder.Entity("PixelChat.Models.AssetReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceBatchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("SourceBatchId");

                    b.HasIndex("ProjectId", "AssetId", "CreatedAt");

                    b.HasIndex("ProjectId", "SourceBatchId", "CreatedAt");

                    b.ToTable("AssetReviewDecisions");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AssistantConversations");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("AssistantMessages");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessageVisual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssistantMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolCallId");

                    b.HasIndex("AssistantMessageId", "SortOrder");

                    b.HasIndex("SourceKind", "SourceRefId");

                    b.ToTable("AssistantMessageVisuals");
                });

            modelBuilder.Entity("PixelChat.Models.BackgroundRemovalExportCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualBackend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlphaMatting")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpaquePixels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RembgPackageVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemovalMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemiTransparentPixels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransparentPixels")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "AssetId");

                    b.HasIndex("AssetId", "SourceImageSha256", "RemovalMethod", "ModelName", "RembgPackageVersion", "AlphaMatting", "OptionsHash")
                        .IsUnique();

                    b.ToTable("BackgroundRemovalExportCaches");
                });

            modelBuilder.Entity("PixelChat.Models.BuiltSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedFrameIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid?>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SheetLayoutId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("SheetLayoutId");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("BuiltSheets");
                });

            modelBuilder.Entity("PixelChat.Models.ChatContextAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("ChatContextAttachments");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CompareReviewSets");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompareReviewSetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompareReviewSetId", "SortOrder");

                    b.HasIndex("CompareReviewSetId", "Kind", "RefId")
                        .IsUnique();

                    b.ToTable("CompareReviewSetItems");
                });

            modelBuilder.Entity("PixelChat.Models.ExportStepCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualBackend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OutputImageSha256");

                    b.HasIndex("ProjectId", "AssetId", "SourceImageSha256");

                    b.HasIndex("ProjectId", "AssetId", "SourceImageSha256", "StepIndex")
                        .IsUnique();

                    b.ToTable("ExportStepCaches");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HideFromOnionSkin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("SourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId");

                    b.HasIndex("SourceRegionId");

                    b.HasIndex("ProjectId", "FrameSetId", "Index");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderedFrameIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedoStackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoStackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("FrameSets");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimationNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimationPromptSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnimationRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnimationRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Background")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditCanvasTransformJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<byte[]>("EditLogicalMaskData")
                        .HasColumnType("BLOB");

                    b.Property<string>("EditSourceContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EditSourceData")
                        .HasColumnType("BLOB");

                    b.Property<int?>("EditSourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EditSourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputMaskIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBulk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainlineModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("png");

                    b.Property<Guid?>("ParentBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromptRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto");

                    b.Property<string>("RawProviderResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipePromptSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewCompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SpriteLogicalSourceData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SpriteProviderMaskData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SpriteTargetJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimationRecipeId");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("PromptRecipeId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("GenerationBatches");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationOutput", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputWithinPrompt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromptIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId", "OutputIndex");

                    b.HasIndex("BatchId", "Status", "OutputIndex");

                    b.ToTable("GenerationOutputs");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationPrompt", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId", "Index");

                    b.ToTable("GenerationPrompts");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationReference", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId", "Index");

                    b.ToTable("GenerationReferences");
                });

            modelBuilder.Entity("PixelChat.Models.ImageMask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinateSpace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("source");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("asset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ImageMasks");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestAuthType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastChatTestCredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestEndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastChatTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestThinkingMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastChatTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThinkingMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders");
                });

            modelBuilder.Entity("PixelChat.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenSecretName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenSecretName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("PixelChat.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveFrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveSpriteFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSpriteMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("source");

                    b.Property<string>("ActiveSpriteRegionIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid?>("ActiveSpriteSourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveWorkspaceMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundPreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("current");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("PromptRecipes");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundPreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("current");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "RecipeId");

                    b.HasIndex("RecipeId", "Version")
                        .IsUnique();

                    b.ToTable("PromptRecipeVersions");
                });

            modelBuilder.Entity("PixelChat.Models.RecipeAssetAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnimationRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromptRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("example");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimationRecipeId");

                    b.HasIndex("AssetId");

                    b.HasIndex("PromptRecipeId");

                    b.HasIndex("ProjectId", "AnimationRecipeId", "SortOrder");

                    b.HasIndex("ProjectId", "PromptRecipeId", "SortOrder");

                    b.ToTable("RecipeAssetAttachments", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeAssetAttachments_OneRecipeParent", "((PromptRecipeId IS NOT NULL AND AnimationRecipeId IS NULL) OR (PromptRecipeId IS NULL AND AnimationRecipeId IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundMode")
                        .HasColumnType("TEXT");

                    b.Property<int>("CellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gutter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorizontalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("center");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ordering")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("rowMajor");

                    b.Property<int>("OuterMargin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Padding")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerticalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bottom");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId");

                    b.HasIndex("ProjectId", "FrameSetId");

                    b.ToTable("SheetLayouts");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId", "Revision");

                    b.ToTable("SpriteAssessments");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteBitmap", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Hash");

                    b.ToTable("SpriteBitmaps");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecificationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId", "Revision");

                    b.ToTable("SpriteExports");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BitmapHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BitmapHash");

                    b.HasIndex("FrameSetId", "Revision", "CacheKey");

                    b.ToTable("SpriteInspections");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("frame");

                    b.Property<string>("ShapeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "SourceAssetId", "Order");

                    b.ToTable("SpriteRegions");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Script")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UndoTarget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId", "Number")
                        .IsUnique();

                    b.ToTable("SpriteRevisions");
                });

            modelBuilder.Entity("PixelChat.Models.StandaloneAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BitmapRevisionAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LinkedToSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BitmapRevisionAssetId");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("SourceRegionId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("StandaloneAssets");
                });

            modelBuilder.Entity("PixelChat.Models.StoredSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoredSecrets");
                });

            modelBuilder.Entity("PixelChat.Models.WorkbenchPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkbenchPreferences");
                });

            modelBuilder.Entity("PixelChat.Models.Anchor", b =>
                {
                    b.HasOne("PixelChat.Models.Frame", "Frame")
                        .WithMany("Anchors")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Anchors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AnimationRecipes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipeVersion", b =>
                {
                    b.HasOne("PixelChat.Models.AnimationRecipe", "AnimationRecipe")
                        .WithMany("Versions")
                        .HasForeignKey("AnimationRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AnimationRecipeVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimationRecipe");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "ParentAsset")
                        .WithMany("ChildAssets")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.AnimationRecipe", "SourceAnimationRecipe")
                        .WithMany()
                        .HasForeignKey("SourceAnimationRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.GenerationBatch", "SourceBatch")
                        .WithMany("OutputAssets")
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.PromptRecipe", "SourcePromptRecipe")
                        .WithMany()
                        .HasForeignKey("SourcePromptRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentAsset");

                    b.Navigation("Project");

                    b.Navigation("SourceAnimationRecipe");

                    b.Navigation("SourceBatch");

                    b.Navigation("SourcePromptRecipe");
                });

            modelBuilder.Entity("PixelChat.Models.AssetReviewDecision", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany("ReviewDecisions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AssetReviewDecisions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.GenerationBatch", "SourceBatch")
                        .WithMany("ReviewDecisions")
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Project");

                    b.Navigation("SourceBatch");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AssistantConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessage", b =>
                {
                    b.HasOne("PixelChat.Models.AssistantConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessageVisual", b =>
                {
                    b.HasOne("PixelChat.Models.AssistantMessage", "AssistantMessage")
                        .WithMany("Visuals")
                        .HasForeignKey("AssistantMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssistantMessage");
                });

            modelBuilder.Entity("PixelChat.Models.BackgroundRemovalExportCache", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PixelChat.Models.BuiltSheet", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "OutputAsset")
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("BuiltSheets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SheetLayout", "SheetLayout")
                        .WithMany("BuiltSheets")
                        .HasForeignKey("SheetLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutputAsset");

                    b.Navigation("Project");

                    b.Navigation("SheetLayout");
                });

            modelBuilder.Entity("PixelChat.Models.ChatContextAttachment", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("ChatContextAttachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("CompareReviewSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSetItem", b =>
                {
                    b.HasOne("PixelChat.Models.CompareReviewSet", "CompareReviewSet")
                        .WithMany("Items")
                        .HasForeignKey("CompareReviewSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompareReviewSet");
                });

            modelBuilder.Entity("PixelChat.Models.ExportStepCache", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", "FrameSet")
                        .WithMany("Frames")
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Frames")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SpriteRegion", "SourceRegion")
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FrameSet");

                    b.Navigation("Project");

                    b.Navigation("SourceRegion");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("FrameSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.HasOne("PixelChat.Models.AnimationRecipe", "AnimationRecipe")
                        .WithMany()
                        .HasForeignKey("AnimationRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.GenerationBatch", "ParentBatch")
                        .WithMany("ChildBatches")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("GenerationBatches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.PromptRecipe", "PromptRecipe")
                        .WithMany()
                        .HasForeignKey("PromptRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnimationRecipe");

                    b.Navigation("ParentBatch");

                    b.Navigation("Project");

                    b.Navigation("PromptRecipe");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationOutput", b =>
                {
                    b.HasOne("PixelChat.Models.GenerationBatch", "Batch")
                        .WithMany("Outputs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationPrompt", b =>
                {
                    b.HasOne("PixelChat.Models.GenerationBatch", "Batch")
                        .WithMany("Prompts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationReference", b =>
                {
                    b.HasOne("PixelChat.Models.GenerationBatch", "Batch")
                        .WithMany("References")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PixelChat.Models.ImageMask", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Masks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.HasOne("PixelChat.Models.LlmProvider", "CredentialSource")
                        .WithMany("ChildModels")
                        .HasForeignKey("CredentialSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSource");
                });

            modelBuilder.Entity("PixelChat.Models.OAuthToken", b =>
                {
                    b.HasOne("PixelChat.Models.LlmProvider", "Provider")
                        .WithMany("OAuthTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("PromptRecipes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipeVersion", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("PromptRecipeVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.PromptRecipe", "Recipe")
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PixelChat.Models.RecipeAssetAttachment", b =>
                {
                    b.HasOne("PixelChat.Models.AnimationRecipe", "AnimationRecipe")
                        .WithMany("Attachments")
                        .HasForeignKey("AnimationRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("RecipeAssetAttachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.PromptRecipe", "PromptRecipe")
                        .WithMany("Attachments")
                        .HasForeignKey("PromptRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AnimationRecipe");

                    b.Navigation("Asset");

                    b.Navigation("Project");

                    b.Navigation("PromptRecipe");
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", "FrameSet")
                        .WithMany("SheetLayouts")
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SheetLayouts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameSet");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteAssessment", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", null)
                        .WithMany()
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelChat.Models.SpriteExport", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", null)
                        .WithMany()
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelChat.Models.SpriteInspection", b =>
                {
                    b.HasOne("PixelChat.Models.SpriteBitmap", null)
                        .WithMany()
                        .HasForeignKey("BitmapHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.FrameSet", null)
                        .WithMany()
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRegion", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SpriteRegions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRevision", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", null)
                        .WithMany()
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelChat.Models.StandaloneAsset", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "BitmapRevisionAsset")
                        .WithMany()
                        .HasForeignKey("BitmapRevisionAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.ArtAsset", "OutputAsset")
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("StandaloneAssets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SpriteRegion", "SourceRegion")
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BitmapRevisionAsset");

                    b.Navigation("OutputAsset");

                    b.Navigation("Project");

                    b.Navigation("SourceRegion");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.Navigation("ChildAssets");

                    b.Navigation("ReviewDecisions");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessage", b =>
                {
                    b.Navigation("Visuals");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.Navigation("Anchors");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.Navigation("Frames");

                    b.Navigation("SheetLayouts");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.Navigation("ChildBatches");

                    b.Navigation("OutputAssets");

                    b.Navigation("Outputs");

                    b.Navigation("Prompts");

                    b.Navigation("References");

                    b.Navigation("ReviewDecisions");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.Navigation("ChildModels");

                    b.Navigation("OAuthTokens");
                });

            modelBuilder.Entity("PixelChat.Models.Project", b =>
                {
                    b.Navigation("Anchors");

                    b.Navigation("AnimationRecipeVersions");

                    b.Navigation("AnimationRecipes");

                    b.Navigation("AssetReviewDecisions");

                    b.Navigation("Assets");

                    b.Navigation("AssistantConversations");

                    b.Navigation("BuiltSheets");

                    b.Navigation("ChatContextAttachments");

                    b.Navigation("CompareReviewSets");

                    b.Navigation("FrameSets");

                    b.Navigation("Frames");

                    b.Navigation("GenerationBatches");

                    b.Navigation("Masks");

                    b.Navigation("PromptRecipeVersions");

                    b.Navigation("PromptRecipes");

                    b.Navigation("RecipeAssetAttachments");

                    b.Navigation("SheetLayouts");

                    b.Navigation("SpriteRegions");

                    b.Navigation("StandaloneAssets");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.Navigation("BuiltSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
