// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PixelChat.Persistence;

#nullable disable

namespace PixelChat.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PixelChat.Models.ActivityArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityRunId", "SortOrder");

                    b.HasIndex("ProjectId", "Kind", "RefId");

                    b.ToTable("ActivityArtifacts");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("system");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryArtifactKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("running");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.HasIndex("ProjectId", "WorkflowKind");

                    b.ToTable("ActivityRuns");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ActivityRunId", "SortOrder");

                    b.ToTable("ActivitySteps");
                });

            modelBuilder.Entity("PixelChat.Models.Anchor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("FrameId", "Name");

                    b.ToTable("Anchors");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnchorStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("recipe-defined");

                    b.Property<string>("AnimationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedFrameBoxesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ExportDefaultsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Facing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameOrderJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid?>("GuideAssetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryExampleSpriteSheetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptScaffold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuideAssetId");

                    b.HasIndex("PrimaryExampleSpriteSheetId");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("AnimationRecipes");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnchorStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("recipe-defined");

                    b.Property<string>("AnimationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimationRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedFrameBoxesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ExportDefaultsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Facing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameOrderJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid?>("GuideAssetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryExampleSpriteSheetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptScaffold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimationRecipeId", "Version")
                        .IsUnique();

                    b.HasIndex("ProjectId", "AnimationRecipeId");

                    b.ToTable("AnimationRecipeVersions");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourcePromptRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePromptRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentAssetId");

                    b.HasIndex("SourceBatchId");

                    b.HasIndex("SourcePromptRecipeId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ArtAssets");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AssistantConversations");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("AssistantMessages");
                });

            modelBuilder.Entity("PixelChat.Models.BackgroundRemovalExportCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualBackend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlphaMatting")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpaquePixels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RembgPackageVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemovalMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemiTransparentPixels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransparentPixels")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "AssetId");

                    b.HasIndex("AssetId", "SourceImageSha256", "RemovalMethod", "ModelName", "RembgPackageVersion", "AlphaMatting", "OptionsHash")
                        .IsUnique();

                    b.ToTable("BackgroundRemovalExportCaches");
                });

            modelBuilder.Entity("PixelChat.Models.BuiltSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedFrameIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid?>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SheetLayoutId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("SheetLayoutId");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("BuiltSheets");
                });

            modelBuilder.Entity("PixelChat.Models.ChatContextAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("ChatContextAttachments");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CompareReviewSets");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompareReviewSetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompareReviewSetId", "SortOrder");

                    b.HasIndex("CompareReviewSetId", "Kind", "RefId")
                        .IsUnique();

                    b.ToTable("CompareReviewSetItems");
                });

            modelBuilder.Entity("PixelChat.Models.ExportStepCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualBackend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceImageSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OutputImageSha256");

                    b.HasIndex("ProjectId", "AssetId", "SourceImageSha256");

                    b.HasIndex("ProjectId", "AssetId", "SourceImageSha256", "StepIndex")
                        .IsUnique();

                    b.ToTable("ExportStepCaches");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BitmapRevisionAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreviewData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PreviewHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviewWidth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("SourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("image/png");

                    b.Property<byte[]>("WorkingData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("WorkingHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingMargin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<DateTime?>("WorkingUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkingWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BitmapRevisionAssetId");

                    b.HasIndex("FrameSetId");

                    b.HasIndex("SourceRegionId");

                    b.HasIndex("ProjectId", "FrameSetId", "Index")
                        .IsUnique();

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlignmentSettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderedFrameIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("PlaybackSettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("FrameSets");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditSourceContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EditSourceData")
                        .HasColumnType("BLOB");

                    b.Property<int?>("EditSourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EditSourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputMaskIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainlineModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputErrorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputStatesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid?>("ParentBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromptRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptRecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawProviderResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("PromptRecipeId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("GenerationBatches");
                });

            modelBuilder.Entity("PixelChat.Models.HistoryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("user");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("running");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "StartedAt");

                    b.ToTable("HistoryTasks");
                });

            modelBuilder.Entity("PixelChat.Models.ImageMask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinateSpace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("source");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("asset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ImageMasks");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteEditSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateAssetIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CropJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid?>("MaskId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModalOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputStatesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("PreviewOverlayActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedCandidateAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedOutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<Guid?>("TargetFrameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetFrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("source");

                    b.Property<Guid?>("TargetSourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MaskId");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("Status = 'pending'");

                    b.HasIndex("SelectedCandidateAssetId");

                    b.HasIndex("TargetFrameId");

                    b.HasIndex("TargetFrameSetId");

                    b.HasIndex("TargetSourceAssetId");

                    b.ToTable("SpriteEditSessions");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestAuthType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastChatTestCredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestEndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastChatTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestThinkingMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastChatTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThinkingMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders");
                });

            modelBuilder.Entity("PixelChat.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenSecretName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenSecretName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("PixelChat.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveFrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveSpriteSheetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveWorkspaceMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSpriteSheetId");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvoidRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExampleAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportDefaultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("PromptRecipes");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvoidRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExampleAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportDefaultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "RecipeId");

                    b.HasIndex("RecipeId", "Version")
                        .IsUnique();

                    b.ToTable("PromptRecipeVersions");
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundMode")
                        .HasColumnType("TEXT");

                    b.Property<int>("CellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FrameSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gutter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorizontalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("center");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ordering")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("rowMajor");

                    b.Property<int>("OuterMargin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Padding")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerticalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bottom");

                    b.HasKey("Id");

                    b.HasIndex("FrameSetId");

                    b.HasIndex("ProjectId", "FrameSetId");

                    b.ToTable("SheetLayouts");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("frame");

                    b.Property<string>("ShapeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "SourceAssetId", "Order");

                    b.ToTable("SpriteRegions");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteSheetDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundMode")
                        .HasColumnType("TEXT");

                    b.Property<int>("CellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FramesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gutter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorizontalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("center");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Padding")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StabilizationJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerticalAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bottom");

                    b.HasKey("Id");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("SpriteSheetDefinitions");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteSheetFrameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AppliedScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<int>("CellHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FootContactsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKeyframe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Phase")
                        .HasColumnType("REAL");

                    b.Property<int>("PivotX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PivotY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreviewData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PreviewHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviewWidth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QaStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepairHistoryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("RootOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShapeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("SourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceImageX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceImageY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpriteHeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SpriteSheetDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpriteWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpriteX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpriteY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("image/png");

                    b.Property<byte[]>("WorkingData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("WorkingHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingMargin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<DateTime?>("WorkingUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkingWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceImageAssetId");

                    b.HasIndex("SpriteSheetDefinitionId");

                    b.HasIndex("ProjectId", "SpriteSheetDefinitionId", "Index")
                        .IsUnique();

                    b.ToTable("SpriteSheetFrameRecords");
                });

            modelBuilder.Entity("PixelChat.Models.StandaloneAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BitmapRevisionAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LinkedToSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BitmapRevisionAssetId");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("SourceRegionId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("StandaloneAssets");
                });

            modelBuilder.Entity("PixelChat.Models.StoredSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoredSecrets");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityArtifact", b =>
                {
                    b.HasOne("PixelChat.Models.ActivityRun", "ActivityRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("ActivityRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("ActivityArtifacts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityRun", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("ActivityRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityStep", b =>
                {
                    b.HasOne("PixelChat.Models.ActivityRun", "ActivityRun")
                        .WithMany("Steps")
                        .HasForeignKey("ActivityRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("ActivitySteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.Anchor", b =>
                {
                    b.HasOne("PixelChat.Models.Frame", "Frame")
                        .WithMany("Anchors")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Anchors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "GuideAsset")
                        .WithMany()
                        .HasForeignKey("GuideAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.SpriteSheetDefinition", "PrimaryExampleSpriteSheet")
                        .WithMany()
                        .HasForeignKey("PrimaryExampleSpriteSheetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AnimationRecipes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideAsset");

                    b.Navigation("PrimaryExampleSpriteSheet");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipeVersion", b =>
                {
                    b.HasOne("PixelChat.Models.AnimationRecipe", "AnimationRecipe")
                        .WithMany("Versions")
                        .HasForeignKey("AnimationRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AnimationRecipeVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimationRecipe");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "ParentAsset")
                        .WithMany("ChildAssets")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.GenerationBatch", "SourceBatch")
                        .WithMany("OutputAssets")
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.PromptRecipe", "SourcePromptRecipe")
                        .WithMany()
                        .HasForeignKey("SourcePromptRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentAsset");

                    b.Navigation("Project");

                    b.Navigation("SourceBatch");

                    b.Navigation("SourcePromptRecipe");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("AssistantConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantMessage", b =>
                {
                    b.HasOne("PixelChat.Models.AssistantConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PixelChat.Models.BackgroundRemovalExportCache", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PixelChat.Models.BuiltSheet", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "OutputAsset")
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("BuiltSheets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SheetLayout", "SheetLayout")
                        .WithMany("BuiltSheets")
                        .HasForeignKey("SheetLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutputAsset");

                    b.Navigation("Project");

                    b.Navigation("SheetLayout");
                });

            modelBuilder.Entity("PixelChat.Models.ChatContextAttachment", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("ChatContextAttachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("CompareReviewSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSetItem", b =>
                {
                    b.HasOne("PixelChat.Models.CompareReviewSet", "CompareReviewSet")
                        .WithMany("Items")
                        .HasForeignKey("CompareReviewSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompareReviewSet");
                });

            modelBuilder.Entity("PixelChat.Models.ExportStepCache", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "BitmapRevisionAsset")
                        .WithMany()
                        .HasForeignKey("BitmapRevisionAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.FrameSet", "FrameSet")
                        .WithMany("Frames")
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Frames")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SpriteRegion", "SourceRegion")
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BitmapRevisionAsset");

                    b.Navigation("FrameSet");

                    b.Navigation("Project");

                    b.Navigation("SourceRegion");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("FrameSets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.HasOne("PixelChat.Models.GenerationBatch", "ParentBatch")
                        .WithMany("ChildBatches")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("GenerationBatches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.PromptRecipe", "PromptRecipe")
                        .WithMany()
                        .HasForeignKey("PromptRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentBatch");

                    b.Navigation("Project");

                    b.Navigation("PromptRecipe");
                });

            modelBuilder.Entity("PixelChat.Models.HistoryTask", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("HistoryTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.ImageMask", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("Masks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteEditSession", b =>
                {
                    b.HasOne("PixelChat.Models.GenerationBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.ImageMask", null)
                        .WithMany()
                        .HasForeignKey("MaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SpriteEditSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", null)
                        .WithMany()
                        .HasForeignKey("SelectedCandidateAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Frame", null)
                        .WithMany()
                        .HasForeignKey("TargetFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.FrameSet", null)
                        .WithMany()
                        .HasForeignKey("TargetFrameSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.ArtAsset", null)
                        .WithMany()
                        .HasForeignKey("TargetSourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.HasOne("PixelChat.Models.LlmProvider", "CredentialSource")
                        .WithMany("ChildModels")
                        .HasForeignKey("CredentialSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSource");
                });

            modelBuilder.Entity("PixelChat.Models.OAuthToken", b =>
                {
                    b.HasOne("PixelChat.Models.LlmProvider", "Provider")
                        .WithMany("OAuthTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("PromptRecipes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipeVersion", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("PromptRecipeVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.PromptRecipe", "Recipe")
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.HasOne("PixelChat.Models.FrameSet", "FrameSet")
                        .WithMany("SheetLayouts")
                        .HasForeignKey("FrameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SheetLayouts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameSet");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteRegion", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SpriteRegions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteSheetDefinition", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "OutputAsset")
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SpriteSheets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutputAsset");

                    b.Navigation("Project");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteSheetFrameRecord", b =>
                {
                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("SpriteSheetFrameRecords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.ArtAsset", "SourceImageAsset")
                        .WithMany()
                        .HasForeignKey("SourceImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.SpriteSheetDefinition", "SpriteSheetDefinition")
                        .WithMany("FrameRecords")
                        .HasForeignKey("SpriteSheetDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SourceImageAsset");

                    b.Navigation("SpriteSheetDefinition");
                });

            modelBuilder.Entity("PixelChat.Models.StandaloneAsset", b =>
                {
                    b.HasOne("PixelChat.Models.ArtAsset", "BitmapRevisionAsset")
                        .WithMany()
                        .HasForeignKey("BitmapRevisionAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelChat.Models.ArtAsset", "OutputAsset")
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.Project", "Project")
                        .WithMany("StandaloneAssets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelChat.Models.SpriteRegion", "SourceRegion")
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BitmapRevisionAsset");

                    b.Navigation("OutputAsset");

                    b.Navigation("Project");

                    b.Navigation("SourceRegion");
                });

            modelBuilder.Entity("PixelChat.Models.ActivityRun", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("PixelChat.Models.AnimationRecipe", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PixelChat.Models.ArtAsset", b =>
                {
                    b.Navigation("ChildAssets");
                });

            modelBuilder.Entity("PixelChat.Models.AssistantConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PixelChat.Models.CompareReviewSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PixelChat.Models.Frame", b =>
                {
                    b.Navigation("Anchors");
                });

            modelBuilder.Entity("PixelChat.Models.FrameSet", b =>
                {
                    b.Navigation("Frames");

                    b.Navigation("SheetLayouts");
                });

            modelBuilder.Entity("PixelChat.Models.GenerationBatch", b =>
                {
                    b.Navigation("ChildBatches");

                    b.Navigation("OutputAssets");
                });

            modelBuilder.Entity("PixelChat.Models.LlmProvider", b =>
                {
                    b.Navigation("ChildModels");

                    b.Navigation("OAuthTokens");
                });

            modelBuilder.Entity("PixelChat.Models.Project", b =>
                {
                    b.Navigation("ActivityArtifacts");

                    b.Navigation("ActivityRuns");

                    b.Navigation("ActivitySteps");

                    b.Navigation("Anchors");

                    b.Navigation("AnimationRecipeVersions");

                    b.Navigation("AnimationRecipes");

                    b.Navigation("Assets");

                    b.Navigation("AssistantConversations");

                    b.Navigation("BuiltSheets");

                    b.Navigation("ChatContextAttachments");

                    b.Navigation("CompareReviewSets");

                    b.Navigation("FrameSets");

                    b.Navigation("Frames");

                    b.Navigation("GenerationBatches");

                    b.Navigation("HistoryTasks");

                    b.Navigation("Masks");

                    b.Navigation("PromptRecipeVersions");

                    b.Navigation("PromptRecipes");

                    b.Navigation("SheetLayouts");

                    b.Navigation("SpriteRegions");

                    b.Navigation("SpriteEditSessions");

                    b.Navigation("SpriteSheetFrameRecords");

                    b.Navigation("SpriteSheets");

                    b.Navigation("StandaloneAssets");
                });

            modelBuilder.Entity("PixelChat.Models.PromptRecipe", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PixelChat.Models.SheetLayout", b =>
                {
                    b.Navigation("BuiltSheets");
                });

            modelBuilder.Entity("PixelChat.Models.SpriteSheetDefinition", b =>
                {
                    b.Navigation("FrameRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
