// Run against an isolated PixelChat host. Requires Playwright and a local Edge installation.
const { chromium } = require(process.env.PIXELCHAT_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
async function main() {
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
        const errors = []; page.on('pageerror', e => errors.push(e.message));
        const connected = page.waitForEvent('websocket', { predicate: socket => socket.url().includes('/_blazor') });
        await page.goto(process.env.PIXELCHAT_TEST_URL || 'http://127.0.0.1:1465');
        const socket = await connected;
        await socket.waitForEvent('framereceived');
        await page.waitForTimeout(500);
        await page.getByRole('button', { name: 'Sprites', exact: true }).click();
        await page.getByRole('button', { name: 'New sprite', exact: true }).click();
        const form = page.locator('.sprite-form').first();
        const name = `Browser fixture ${Date.now()}`;
        await form.getByLabel('Name', { exact: true }).fill(name);
        await form.getByLabel('Width', { exact: true }).fill('8');
        await form.getByLabel('Height', { exact: true }).fill('8');
        await form.getByRole('button', { name: 'Create', exact: true }).click();
        const editor = page.locator('.native-editor'); const canvas = page.getByLabel('Sprite drawing canvas');
        await page.waitForFunction(name => document.querySelector('.native-toolbar strong')?.textContent === name, name);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas')?.dataset.renderRevision === '0');
        async function revision(number) { await page.waitForFunction(n => document.querySelector('.native-editor')?.dataset.revision === String(n), number); }
        async function pixel(x, y) { return await canvas.evaluate((c, p) => [...c.getContext('2d').getImageData(p.x, p.y, 1, 1).data], { x, y }); }
        const rect = await canvas.boundingBox();
        await page.mouse.click(rect.x + 2.5 * rect.width / 8, rect.y + 3.5 * rect.height / 8);
        await revision(1); await page.waitForFunction(() => document.querySelector('.native-editor canvas').getContext('2d').getImageData(2,3,1,1).data[3] === 255);
        assert.deepEqual(await pixel(2, 3), [255,128,64,255]); assert.equal((await pixel(3, 3))[3], 0);
        await editor.getByRole('button', { name: 'Undo', exact: true }).click(); await revision(2);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas').getContext('2d').getImageData(2,3,1,1).data[3] === 0);
        await editor.getByRole('button', { name: 'Redo', exact: true }).click(); await revision(3);
        await editor.getByRole('button', { name: 'Add', exact: true }).click(); await revision(4);
        assert.equal(await editor.locator('.layer-row').count(), 2);
        await editor.getByRole('button', { name: 'Duplicate frame', exact: true }).click(); await revision(5);
        assert.equal(await editor.locator('.frame-card').count(), 2);
        await editor.locator('.frame-card').last().click();
        await editor.getByLabel('Duration (ms)', { exact: true }).fill('175');
        await editor.getByLabel('Duration (ms)', { exact: true }).press('Tab'); await revision(6);
        await editor.getByRole('button', { name: 'History', exact: true }).click();
        await editor.locator('.history details').nth(6).waitFor();
        assert.equal(await editor.locator('.history details').count(), 7);
        await page.reload(); await page.getByRole('button', { name: 'Sprites', exact: true }).click();
        await revision(6); assert.equal(await editor.locator('.frame-card').count(), 2);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas')?.dataset.renderRevision === '6');
        assert.deepEqual(await pixel(2, 3), [255,128,64,255]);
        await editor.getByRole('button', { name: 'AI', exact: true }).click();
        await editor.getByRole('button', { name: 'Validate every frame', exact: true }).click();
        await editor.getByText('2 frames measured at r6', { exact: false }).waitFor();
        await editor.getByRole('button', { name: 'Preview preparation', exact: true }).click();
        await editor.locator('.sprite-ai figure').nth(1).waitFor();
        assert.equal(await editor.locator('.sprite-ai [role=alert]').count(), 0);
        await editor.getByRole('button', { name: 'Layers', exact: true }).click();
        const artwork = editor.locator('.layer-row').last();
        await artwork.getByLabel('Show', { exact: true }).uncheck(); await revision(7);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas').getContext('2d').getImageData(2,3,1,1).data[3] === 0);
        await artwork.getByLabel('Show', { exact: true }).check(); await revision(8);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas').getContext('2d').getImageData(2,3,1,1).data[3] === 255);
        await editor.getByRole('button', { name: 'Properties', exact: true }).click();
        await editor.getByLabel('Clip name', { exact: true }).fill('Reverse action');
        await editor.getByLabel('Last', { exact: true }).fill('2');
        await editor.getByLabel('Playback direction', { exact: true }).selectOption('reverse');
        await editor.getByLabel('Loop', { exact: true }).uncheck();
        await editor.getByRole('button', { name: 'Save clip', exact: true }).click(); await revision(9);
        await editor.getByRole('button', { name: 'Play', exact: true }).click();
        await page.waitForFunction(() => document.querySelector('canvas.native-playback')?.dataset.frameIndex === '1');
        await page.waitForTimeout(400);
        assert.equal(await editor.locator('canvas.native-playback').getAttribute('data-frame-index'), '1');
        assert.equal(await editor.locator('canvas.native-playback').getAttribute('data-duration-ms'), '100');
        await editor.getByRole('button', { name: 'Stop playback', exact: true }).click();
        await editor.getByRole('button', { name: 'Export', exact: true }).click();
        await editor.getByRole('button', { name: 'Create export', exact: true }).click();
        const downloadLink = editor.locator('.sprite-download').first(); await downloadLink.waitFor();
        const response = await page.request.get(new URL(await downloadLink.getAttribute('href'), page.url()).href);
        assert.equal(response.status(), 200);
        const bundle = await response.body(); assert.ok(bundle.length > 500);
        await page.getByRole('button', { name: 'Import artwork', exact: true }).click();
        await page.getByLabel('Import native / atlas / frames bundle').setInputFiles({ name: 'roundtrip.pixelchat.zip', mimeType: 'application/zip', buffer: bundle });
        await revision(0);
        await page.waitForFunction(() => document.querySelector('.native-editor canvas')?.dataset.renderRevision === '0');
        assert.deepEqual(await pixel(2, 3), [255,128,64,255]);
        assert.equal(await editor.locator('.layer-row').count(), 2);
        assert.equal(await editor.locator('.frame-card').count(), 2);
        assert.equal(await editor.locator('.frame-card').last().locator('small').textContent(), '175 ms');
        await editor.getByRole('button', { name: 'Properties', exact: true }).click();
        await editor.locator('.clip-controls select').first().selectOption('Reverse action');
        await page.waitForFunction(() => document.querySelector('[aria-label="Playback direction"]')?.value === 'reverse');
        assert.equal(await editor.getByLabel('Playback direction', { exact: true }).inputValue(), 'reverse');
        assert.equal(await editor.getByLabel('Loop', { exact: true }).isChecked(), false);
        if (process.env.PIXELCHAT_TEST_SCREENSHOT) await page.screenshot({ path: process.env.PIXELCHAT_TEST_SCREENSHOT, fullPage: true });
        assert.deepEqual(errors, []);
        console.log('PASS: drawing coordinates/pixels, undo/redo, layers/visibility, frames/timing, history/reopen, all-frame diagnostics, preparation PNGs, reverse one-shot playback, native export/reimport.');
    } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
