using PixelChat.Models;

namespace PixelChat.Art;

public interface IArtWorkflowService
{
    Task<ProjectView> EnsureDefaultProjectAsync(CancellationToken cancellationToken = default);
    Task<ProjectView> CreateProjectAsync(string name, CancellationToken cancellationToken = default);
    Task<WorkbenchView> GetWorkbenchAsync(Guid? projectId = null, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetAssetPreviewImageAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetAssetFullImageAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetMaskImageAsync(Guid projectId, Guid maskId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetSpriteFramePreviewImageAsync(Guid projectId, Guid frameId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetChatVisualImageAsync(Guid projectId, Guid visualId, bool preview, CancellationToken cancellationToken = default);
    Task<ArtAssetExportView> GetAssetForExportAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<string> ListAssetsJsonAsync(Guid projectId, string? kind = null, string? query = null, bool? favorite = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadAssetJsonAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<string> ListPromptRecipesJsonAsync(Guid projectId, string? query = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadPromptRecipeJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListAnimationRecipesJsonAsync(Guid projectId, string? query = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadAnimationRecipeJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListGenerationBatchesJsonAsync(Guid projectId, string? status = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadGenerationBatchJsonAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task<string> ListSpriteSheetsJsonAsync(Guid projectId, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadSpriteSheetJsonAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewView> BuildSpriteAnimationReviewAsync(Guid projectId, Guid spriteSheetId, int maxFrames = 12, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetAnnotatedSheetAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetAnnotatedSheetAsync(Guid projectId, Guid spriteSheetId, IReadOnlyList<SpriteSheetRejectedSegmentView> rejectedSegments, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetDetectionAnnotatedSheetAsync(Guid projectId, SpriteSheetDetectionResult detection, CancellationToken cancellationToken = default);
    Task<BackgroundRemovalExportCacheView?> GetBackgroundRemovalExportCacheAsync(Guid projectId, Guid assetId, BackgroundRemovalExportCacheRequest request, CancellationToken cancellationToken = default);
    Task<BackgroundRemovalExportCacheView> SaveBackgroundRemovalExportCacheAsync(Guid projectId, Guid assetId, SaveBackgroundRemovalExportCacheRequest request, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<ExportStepCacheView>> GetExportStepCacheAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ExportStepCacheView> SaveExportStepCacheAsync(Guid projectId, Guid assetId, SaveExportStepCacheRequest request, CancellationToken cancellationToken = default);
    Task ClearExportStepCacheAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDetectionResult> DetectSpriteSheetFramesAsync(Guid projectId, SpriteSheetDetectionRequest request, CancellationToken cancellationToken = default);
    Task<RepairSpriteSheetFramesResult> RepairSpriteSheetFramesAsync(Guid projectId, RepairSpriteSheetFramesRequest request, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> StartSpriteSheetEditAsync(Guid projectId, Guid sourceAssetId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> ComposeSpriteSheetFromImagesAsync(Guid projectId, ComposeSpriteSheetFromImagesRequest request, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> AutosaveSpriteSheetLayoutAsync(Guid projectId, AutosaveSpriteSheetLayoutRequest request, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> NormalizeSpriteSheetAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> ExpandSpriteSheetFramesToCellAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> UpdateSpriteSheetFramesAsync(Guid projectId, UpdateSpriteSheetFramesRequest request, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> AdjustSpriteSheetFrameBoxAsync(Guid projectId, AdjustSpriteSheetFrameBoxRequest request, CancellationToken cancellationToken = default);
    Task<StabilizeSpriteSheetFramesResult> StabilizeSpriteSheetFramesAsync(Guid projectId, StabilizeSpriteSheetFramesRequest request, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> ClearSpriteSheetStabilizationAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> DeleteSpriteSheetFrameAsync(Guid projectId, Guid spriteSheetId, Guid frameId, CancellationToken cancellationToken = default);
    Task<SpriteSheetDefinitionView> ResetSpriteSheetToOriginalAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetRepairAnnotatedSheetAsync(Guid projectId, RepairSpriteSheetFramesResult repair, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetStabilizationAnnotatedSheetAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView> BuildSpriteSheetStabilizationAnnotatedSheetAsync(Guid projectId, Guid spriteSheetId, SpriteSheetStabilizationView stabilization, CancellationToken cancellationToken = default);
    Task<SpriteFrameWorkingView> IsolateSpriteFrameAsync(Guid projectId, Guid spriteSheetId, int frameIndex, int? margin = null, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<SpriteFrameWorkingView>> SplitSpriteSheetFramesAsync(Guid projectId, Guid spriteSheetId, int? margin = null, CancellationToken cancellationToken = default);
    Task<SpriteFrameWorkingView> GetSpriteFrameWorkingImageAsync(Guid projectId, Guid spriteSheetId, int frameIndex, CancellationToken cancellationToken = default);
    Task<SpriteAnimationReviewImageView?> BuildSpriteFrameGridImageAsync(Guid projectId, Guid spriteSheetId, int frameIndex, CancellationToken cancellationToken = default);
    Task<SpriteFrameWorkingView> EraseSpriteFrameRegionsAsync(Guid projectId, EraseSpriteFrameRegionsRequest request, CancellationToken cancellationToken = default);
    Task<SpriteFrameWorkingView> EditSpriteFrameAsync(Guid projectId, EditSpriteFrameRequest request, CancellationToken cancellationToken = default);
    Task<SpriteFrameWorkingView> ClearSpriteFrameWorkingImageAsync(Guid projectId, Guid spriteSheetId, int frameIndex, CancellationToken cancellationToken = default);
    Task<ReassembleSpriteSheetResult> ReassembleSpriteSheetAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task SelectSpriteSheetAsync(Guid projectId, Guid spriteSheetId, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<ChatContextAttachmentView>> AttachSpriteSheetFramesAsync(Guid projectId, Guid spriteSheetId, IReadOnlyList<Guid>? frameIds = null, CancellationToken cancellationToken = default);
    Task<string?> BuildSpriteSheetManifestJsonAsync(Guid projectId, Guid assetId, string pngFileName, CancellationToken cancellationToken = default);
    Task SetWorkspaceModeAsync(Guid projectId, WorkspaceMode mode, CancellationToken cancellationToken = default);
    Task SelectBatchAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task<GenerationBatchView> StartGenerateImagesAsync(Guid projectId, GenerateImagesRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> GenerateBatchOutputAsync(Guid projectId, Guid batchId, int outputIndex, CancellationToken cancellationToken = default, IProgress<ImageProviderProgress>? progress = null);
    Task<GenerationBatchView> StartEditImageAsync(Guid projectId, EditImageRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> GenerateEditBatchOutputAsync(Guid projectId, Guid batchId, int outputIndex, CancellationToken cancellationToken = default, IProgress<ImageProviderProgress>? progress = null);
    Task MarkGenerationBatchOutputStateAsync(Guid projectId, Guid batchId, GenerationOutputStateView outputState, CancellationToken cancellationToken = default);
    Task MarkGenerationBatchOutputFailedAsync(Guid projectId, Guid batchId, int outputIndex, string error, CancellationToken cancellationToken = default);
    Task MarkGenerationBatchOutputFailedAsync(Guid projectId, Guid batchId, GenerationOutputErrorView outputError, CancellationToken cancellationToken = default);
    Task<GenerationBatchView> CompleteGenerationBatchAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task ReconcileInterruptedGenerationBatchesAsync(CancellationToken cancellationToken = default);
    Task<GenerationBatchView> GenerateImagesAsync(Guid projectId, GenerateImagesRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> ImportAssetAsync(Guid projectId, ImportAssetRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> CreateCropAssetAsync(Guid projectId, CropAssetRequest request, CancellationToken cancellationToken = default);
    Task<ExtractRegionAsAssetResult> ExtractRegionAsAssetAsync(Guid projectId, ExtractRegionAsAssetRequest request, CancellationToken cancellationToken = default);
    Task<ImageMaskView> UpsertAssetMaskAsync(Guid projectId, Guid assetId, string maskDataUrl, string label, CancellationToken cancellationToken = default);
    Task ClearAssetMaskAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> SavePromptRecipeAsync(Guid projectId, SavePromptRecipeRequest request, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> UpdatePromptRecipeAsync(Guid projectId, Guid recipeId, UpdatePromptRecipeRequest request, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> DuplicatePromptRecipeAsync(Guid projectId, Guid recipeId, string? name = null, string source = "user", string changeSummary = "", CancellationToken cancellationToken = default);
    Task<PromptRecipeView> ReplacePromptRecipeAttachmentsAsync(Guid projectId, Guid recipeId, IReadOnlyList<RecipeAssetAttachmentRequest> attachments, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PromptRecipeVersionView>> ListPromptRecipeVersionsAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListPromptRecipeVersionsJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> RevertPromptRecipeAsync(Guid projectId, Guid recipeId, int version, string source, CancellationToken cancellationToken = default);
    Task DeletePromptRecipeAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> SaveAnimationRecipeAsync(Guid projectId, SaveAnimationRecipeRequest request, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> UpdateAnimationRecipeAsync(Guid projectId, Guid recipeId, UpdateAnimationRecipeRequest request, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> ReplaceAnimationRecipeAttachmentsAsync(Guid projectId, Guid recipeId, IReadOnlyList<RecipeAssetAttachmentRequest> attachments, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<AnimationRecipeVersionView>> ListAnimationRecipeVersionsAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListAnimationRecipeVersionsJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> RevertAnimationRecipeAsync(Guid projectId, Guid recipeId, int version, string source, CancellationToken cancellationToken = default);
    Task DeleteAnimationRecipeAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationGuideRenderView> GenerateAnimationGuideAsync(Guid projectId, GenerateAnimationGuideRequest request, CancellationToken cancellationToken = default);
    Task MarkAssetAsync(Guid projectId, Guid assetId, bool? favorite, string? notes, CancellationToken cancellationToken = default);
    Task DeleteAssetAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ChatContextAttachmentView> AttachContextAsync(Guid projectId, ChatContextAttachmentType type, Guid refId, string? label = null, CancellationToken cancellationToken = default);
    Task RemoveContextAsync(Guid projectId, Guid attachmentId, CancellationToken cancellationToken = default);
    Task ClearContextAsync(Guid projectId, CancellationToken cancellationToken = default);
    Task<CompareReviewSetView> SetCompareReviewSetAsync(Guid projectId, SetCompareReviewSetRequest request, CancellationToken cancellationToken = default);
    Task<CompareReviewSetView> AddCompareReviewItemsAsync(Guid projectId, AddCompareReviewItemsRequest request, CancellationToken cancellationToken = default);
    Task RemoveCompareReviewItemAsync(Guid projectId, Guid itemId, CancellationToken cancellationToken = default);
    Task ClearCompareReviewSetAsync(Guid projectId, CancellationToken cancellationToken = default);
    Task<string> GetWorkspaceStateJsonAsync(Guid projectId, CancellationToken cancellationToken = default);
}
