using PixelChat.Models;

namespace PixelChat.Art;

public interface IArtWorkflowService
{
    Task<ProjectView> EnsureDefaultProjectAsync(CancellationToken cancellationToken = default);
    Task<ProjectView> CreateProjectAsync(string name, CancellationToken cancellationToken = default);
    Task<WorkbenchView> GetWorkbenchAsync(Guid? projectId = null, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetAssetPreviewImageAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetAssetFullImageAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetMaskImageAsync(Guid projectId, Guid maskId, CancellationToken cancellationToken = default);
    Task<ImageBinaryView> GetChatVisualImageAsync(Guid projectId, Guid visualId, bool preview, CancellationToken cancellationToken = default);
    Task<ArtAssetExportView> GetAssetForExportAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<string> ListAssetsJsonAsync(Guid projectId, string? kind = null, string? query = null, bool? favorite = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadAssetJsonAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<string> ListPromptRecipesJsonAsync(Guid projectId, string? query = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadPromptRecipeJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListAnimationRecipesJsonAsync(Guid projectId, string? query = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadAnimationRecipeJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<MotionClipView>> ListMotionClipsAsync(string? query = null, string? animationKind = null, bool? loop = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ListMotionClipsJsonAsync(string? query = null, string? animationKind = null, bool? loop = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ListGenerationBatchesJsonAsync(Guid projectId, string? status = null, int? limit = null, CancellationToken cancellationToken = default);
    Task<string> ReadGenerationBatchJsonAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task<BackgroundRemovalExportCacheView?> GetBackgroundRemovalExportCacheAsync(Guid projectId, Guid assetId, BackgroundRemovalExportCacheRequest request, CancellationToken cancellationToken = default);
    Task<BackgroundRemovalExportCacheView> SaveBackgroundRemovalExportCacheAsync(Guid projectId, Guid assetId, SaveBackgroundRemovalExportCacheRequest request, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<ExportStepCacheView>> GetExportStepCacheAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ExportStepCacheView> SaveExportStepCacheAsync(Guid projectId, Guid assetId, SaveExportStepCacheRequest request, CancellationToken cancellationToken = default);
    Task ClearExportStepCacheAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task SetWorkspaceModeAsync(Guid projectId, WorkspaceMode mode, CancellationToken cancellationToken = default);
    Task SelectBatchAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task<GenerationBatchView> StartGenerateImagesAsync(Guid projectId, GenerateImagesRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> GenerateBatchOutputAsync(Guid projectId, Guid batchId, int outputIndex, CancellationToken cancellationToken = default, IProgress<ImageProviderProgress>? progress = null);
    Task<GenerationBatchView> StartEditImageAsync(Guid projectId, EditImageRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> GenerateEditBatchOutputAsync(Guid projectId, Guid batchId, int outputIndex, CancellationToken cancellationToken = default, IProgress<ImageProviderProgress>? progress = null);
    Task MarkGenerationBatchOutputStateAsync(Guid projectId, Guid batchId, GenerationOutputStateView outputState, CancellationToken cancellationToken = default);
    Task MarkGenerationBatchOutputFailedAsync(Guid projectId, Guid batchId, int outputIndex, string error, CancellationToken cancellationToken = default);
    Task MarkGenerationBatchOutputFailedAsync(Guid projectId, Guid batchId, GenerationOutputErrorView outputError, CancellationToken cancellationToken = default);
    Task<GenerationBatchView> CompleteGenerationBatchAsync(Guid projectId, Guid batchId, CancellationToken cancellationToken = default);
    Task ReconcileInterruptedGenerationBatchesAsync(CancellationToken cancellationToken = default);
    Task<GenerationBatchView> GenerateImagesAsync(Guid projectId, GenerateImagesRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> ImportAssetAsync(Guid projectId, ImportAssetRequest request, CancellationToken cancellationToken = default);
    Task<ArtAssetView> CreateCropAssetAsync(Guid projectId, CropAssetRequest request, CancellationToken cancellationToken = default);
    Task<ExtractRegionAsAssetResult> ExtractRegionAsAssetAsync(Guid projectId, ExtractRegionAsAssetRequest request, CancellationToken cancellationToken = default);
    Task<ImageMaskView> UpsertAssetMaskAsync(Guid projectId, Guid assetId, string maskDataUrl, string label, CancellationToken cancellationToken = default);
    Task ClearAssetMaskAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> SavePromptRecipeAsync(Guid projectId, SavePromptRecipeRequest request, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> UpdatePromptRecipeAsync(Guid projectId, Guid recipeId, UpdatePromptRecipeRequest request, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> DuplicatePromptRecipeAsync(Guid projectId, Guid recipeId, string? name = null, string source = "user", string changeSummary = "", CancellationToken cancellationToken = default);
    Task<PromptRecipeView> ReplacePromptRecipeAttachmentsAsync(Guid projectId, Guid recipeId, IReadOnlyList<RecipeAssetAttachmentRequest> attachments, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PromptRecipeVersionView>> ListPromptRecipeVersionsAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListPromptRecipeVersionsJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<PromptRecipeView> RevertPromptRecipeAsync(Guid projectId, Guid recipeId, int version, string source, CancellationToken cancellationToken = default);
    Task DeletePromptRecipeAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> SaveAnimationRecipeAsync(Guid projectId, SaveAnimationRecipeRequest request, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> UpdateAnimationRecipeAsync(Guid projectId, Guid recipeId, UpdateAnimationRecipeRequest request, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> ReplaceAnimationRecipeAttachmentsAsync(Guid projectId, Guid recipeId, IReadOnlyList<RecipeAssetAttachmentRequest> attachments, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<AnimationRecipeVersionView>> ListAnimationRecipeVersionsAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<string> ListAnimationRecipeVersionsJsonAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationRecipeView> RevertAnimationRecipeAsync(Guid projectId, Guid recipeId, int version, string source, CancellationToken cancellationToken = default);
    Task DeleteAnimationRecipeAsync(Guid projectId, Guid recipeId, CancellationToken cancellationToken = default);
    Task<AnimationGuidePreviewView> PreviewAnimationGuideAsync(Guid projectId, GenerateAnimationGuideRequest request, CancellationToken cancellationToken = default);
    Task<AnimationGuideRenderView> GenerateAnimationGuideAsync(Guid projectId, GenerateAnimationGuideRequest request, CancellationToken cancellationToken = default);
    Task MarkAssetAsync(Guid projectId, Guid assetId, bool? favorite, string? notes, CancellationToken cancellationToken = default);
    Task<ArtAssetView> RenameAssetAsync(Guid projectId, Guid assetId, string label, CancellationToken cancellationToken = default);
    Task DeleteAssetAsync(Guid projectId, Guid assetId, CancellationToken cancellationToken = default);
    Task<ChatContextAttachmentView> AttachContextAsync(Guid projectId, ChatContextAttachmentType type, Guid refId, string? label = null, CancellationToken cancellationToken = default);
    Task RemoveContextAsync(Guid projectId, Guid attachmentId, CancellationToken cancellationToken = default);
    Task ClearContextAsync(Guid projectId, CancellationToken cancellationToken = default);
    Task<CompareReviewSetView> SetCompareReviewSetAsync(Guid projectId, SetCompareReviewSetRequest request, CancellationToken cancellationToken = default);
    Task<CompareReviewSetView> AddCompareReviewItemsAsync(Guid projectId, AddCompareReviewItemsRequest request, CancellationToken cancellationToken = default);
    Task RemoveCompareReviewItemAsync(Guid projectId, Guid itemId, CancellationToken cancellationToken = default);
    Task ClearCompareReviewSetAsync(Guid projectId, CancellationToken cancellationToken = default);
    Task<string> GetWorkspaceStateJsonAsync(Guid projectId, CancellationToken cancellationToken = default);
}
